#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fakeroot
Version  : 1.23
Release  : 4
URL      : http://http.debian.net/debian/pool/main/f/fakeroot/fakeroot_1.23.orig.tar.xz
Source0  : http://http.debian.net/debian/pool/main/f/fakeroot/fakeroot_1.23.orig.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: fakeroot-bin
Requires: fakeroot-license
BuildRequires : acl-dev
BuildRequires : attr-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : buildreq-cpan
BuildRequires : gettext-bin
BuildRequires : libcap-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : util-linux
Patch1: nodoc.patch

%description
fakeroot can be built to either use SYSV IPC or TCP for message passing.
Cases for which the SYSV IPC version fails or causes problems but for
which fakeroot-tcp has been observed to work well include the items
listed below.

%package bin
Summary: bin components for the fakeroot package.
Group: Binaries
Requires: fakeroot-license

%description bin
bin components for the fakeroot package.


%package dev
Summary: dev components for the fakeroot package.
Group: Development
Requires: fakeroot-bin
Provides: fakeroot-devel

%description dev
dev components for the fakeroot package.


%package license
Summary: license components for the fakeroot package.
Group: Default

%description license
license components for the fakeroot package.


%prep
%setup -q -n fakeroot-1.23
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535345014
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1535345014
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/fakeroot
cp COPYING %{buildroot}/usr/share/doc/fakeroot/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/faked
/usr/bin/fakeroot

%files dev
%defattr(-,root,root,-)
/usr/lib64/libfakeroot-0.so
/usr/lib64/libfakeroot.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/fakeroot/COPYING
