#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fakeroot
Version  : 1.28
Release  : 10
URL      : https://mirrors.kernel.org/debian/pool/main/f/fakeroot/fakeroot_1.28.orig.tar.gz
Source0  : https://mirrors.kernel.org/debian/pool/main/f/fakeroot/fakeroot_1.28.orig.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: fakeroot-bin = %{version}-%{release}
Requires: fakeroot-lib = %{version}-%{release}
Requires: fakeroot-license = %{version}-%{release}
BuildRequires : acl-dev
BuildRequires : attr-dev
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : buildreq-cpan
BuildRequires : gettext-bin
BuildRequires : libcap-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : util-linux
Patch1: nodoc.patch

%description
fakeroot can be built to either use SYSV IPC or TCP for message passing.
Cases for which the SYSV IPC version fails or causes problems but for
which fakeroot-tcp has been observed to work well include the items
listed below.

%package bin
Summary: bin components for the fakeroot package.
Group: Binaries
Requires: fakeroot-license = %{version}-%{release}

%description bin
bin components for the fakeroot package.


%package lib
Summary: lib components for the fakeroot package.
Group: Libraries
Requires: fakeroot-license = %{version}-%{release}

%description lib
lib components for the fakeroot package.


%package license
Summary: license components for the fakeroot package.
Group: Default

%description license
license components for the fakeroot package.


%prep
%setup -q -n fakeroot-1.28
cd %{_builddir}/fakeroot-1.28
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1646767929
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
# VERBOSE=x enables debug mode...
make VERBOSE=x V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1646767929
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fakeroot
cp %{_builddir}/fakeroot-1.28/COPYING %{buildroot}/usr/share/package-licenses/fakeroot/842745cb706f8f2126506f544492f7a80dbe29b3
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/faked
/usr/bin/fakeroot

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfakeroot-0.so
/usr/lib64/libfakeroot.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fakeroot/842745cb706f8f2126506f544492f7a80dbe29b3
